### ISSUE TITLE
NRF52840-DONGLE

### ISSUE THREAD

**Issue by gerisse** [virtualabs/btlejack#32]
hello
i would like to know if the dongle 	
NRF52840-DONGLE (here : https://fr.farnell.com/nordic-semiconductor/nrf52840-dongle/module-bluetooth-v5-2mbps/dp/2902521?st=nrf52 ) runs well qith this software ? Thanks

**Comment by virtualabs** [comment]
This software has been designed for the nRF51822 SoC, and will only work with this chip (at the moment).
