### ISSUE TITLE
Unable to flash Firmware to micro:bit device

### ISSUE THREAD

**Issue by tom-x1** [virtualabs/btlejack#38]
I constantly get the error message:

`The transfer timed out.`

Any Ideas whats wrong here? 
Content of DETAILS.TXT:

# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 0000000051114e450017800d000000310000000097969901
HIC ID: 97969901
Auto Reset: 0
Automation allowed: 1
Overflow detection: 0
Daplink Mode: Bootloader
Bootloader Version: 0243
Git SHA: b403a07e3696cee1e116d44cbdd64446e056ce38
Local Mods: 0
USB Interfaces: MSD
Bootloader CRC: 0x32eb3cfd
Interface CRC: 0x07911068
Remount count: 4

**Comment by virtualabs** [comment]
Looks like you're connecting your Micro:Bit to your computer while pressing the reset button. Simply plug in your Micro:Bit (without pressing anything), access the mass storage device with a file explorer, and then try flashing by copy/paste the firmware file to the Micro:Bit.
