### ISSUE TITLE
Sending captured data to a named pipe 

### ISSUE THREAD

**Issue by PavelPerkov** [virtualabs/btlejack#39]
Hello 
I am using Raspberry PI with Microbit board to capture BLE connection. It works without problem, I write data into .pcap file and afterfords read it via Wireshark. But I would like to have opportinity to monitor all packets live. 
I treid to make pipe, connect it in Wireshark, and send into that pipe .pcap file. 

$ mkfifo /tmp/sharkfin
$ wireshark -k -i /tmp/sharkfin &
$ cat capture.pcap > /tmp/sharkfin &

The same time in this file I write captured data

$ sudo btlejack -c any -x nordic -o capture.pcap

Becouse of command cat, it is not like live, I have to start new session in Wireshark to see new packages every time. I thought, maybe can i send data directly in pipe without any files? somethink like that 
 $ sudo btlejack -c any -x nordic -o /tmp/sharkfin
Or do I have other ways? 
Thanks in advance!

**Comment by lissafox** [comment]
you can find solution in this tutorial: https://archive.freaklabs.org/index.php/tutorials/software/feeding-the-shark-turning-the-freakduino-into-a-realtime-wireless-protocol-analyzer-with-wireshark.html

some places in this source code can be helpful for you!
