### ISSUE TITLE
Print a warning if an invalid -x option is passed

### ISSUE THREAD

**Issue by yath** [virtualabs/btlejack#44]
Hi,

btlejack currently falls back to `-x pcap` if an invalid option for -x is passed. It just took me a while to realize that I had typed `ll_pcap` rather than `ll_phdr`, and btlejack bailing an error (or printing a warning; but that would probably scroll out of sight easily) in that case would be nice.

Thanks,
Sebastian

**Comment by virtualabs** [comment]
Fixed in version 2.0, only available on github for now.
