### ISSUE TITLE
btlejack -s with no output

### ISSUE THREAD

**Issue by new-to-btle** [virtualabs/btlejack#51]
Dear all, 
fist of all, I'm new to linux and btlejack. Using Microbit with btlejack -s there is no output after "enumerating" even if I have several blutooth connections established.
I'm using a MX Linux and the Terminal.
What i my fault. 
Version of btlejack after installation is v 1.3
Thanks in advance

**Comment by virtualabs** [comment]
Are they Bluetooth connections or Bluetooth Low Energy connections ?

**Comment by new-to-btle** [comment]
Hi I guess both,

one connction to blutooth speaker

2 connections to bycycle lights

But again, I'm a complete new user without experience

Thank you

 

Gesendet: Dienstag, 24. September 2019 um 21:43 Uhr
Von: "Damien Cauquil" <notifications@github.com>
An: virtualabs/btlejack <btlejack@noreply.github.com>
Cc: new-to-btle <am@38.de>, Author <author@noreply.github.com>
Betreff: Re: [virtualabs/btlejack] btlejack -s with no output (#51)


Are they Bluetooth connections or Bluetooth Low Energy connections ?

**Comment by new-to-btle** [comment]
PLease close the ticket. It was my fault to use the device, Now it works.
