### ISSUE TITLE
Passive Radiator?

### ISSUE THREAD

**Issue by ArcadeHustle** [virtualabs/btlejack#59]
Can this code be used to passively retransmit packets it sees? I would like to test some passive entry systems that rely on the proximity of the beacons. I'd like to capture them in a remote location and real time replay them (over ethernet) to a different location for example.

**Comment by RCayre** [comment]
If you want to replay advertisements, btlejack is not able to sniff or transmit advertisements yet. However, the hardware supports it, so you can easily add these features if you modify the code of the firmware.

**Comment by virtualabs** [comment]
RCayre is right. Btlejack does not handle this use case, as it is not able to transmit easily an arbitrary packet.
