### ISSUE TITLE
pcap file with zero bytes

### ISSUE THREAD

**Issue by milanmilenkovic** [virtualabs/btlejack#63]
I installed btlejack on a raspberry pi 3 using a micro:bit connected to it. 
Sniffing a connection works well but trying to export the sniff to a file does not work. 
It always creates the file with zero bytes.

- The command i use is:

> btlejack -x pcap -o test.pcap -c <mac_add>

I also tried all -x options and I got the same issue. 
Also if the -x and -o options are passed after the MAC address it is same behaviour.

**Comment by virtualabs** [comment]
Does btlejack capture a BTLE connection ? Do you see some packets displayed by btlejack when you connect to your BTLE device ?

**Comment by fr0zenrain** [comment]
same here, it's seems  not work.
