### ISSUE TITLE
btlejack complete uninstall

### ISSUE THREAD

**Issue by dalaranunion** [virtualabs/btlejack#76]
Hello thanks for this, 

I was wondering if there is a way to completely uninstall btlejack from my Mac (10.15.7)?

I did the mistake of installing it via "setup.py" (which I think is called "easy_install"?) in native Mac's Python. I then removed the btlejack files from native python and installed btlejack on python3 `pip3 install btlejack`. 

However, when running btlejack on the terminal it returns `-bash: /usr/local/bin/btlejack: No such file or directory`.

I somewhat know that this is not a btlejack "issue" but I am a newbie with Python and its enviroment. I tried to read the setup.py file to see what files to find and where to delete them but I was wondering if you could offer a helping hand. 

Is there any way to completely remove btlejack from python (native mac's python) or to re-direct the bash terminal to look into python3 library instead of python for btlejack?

I hope the above makes sense.

Thanks

**Comment by virtualabs** [comment]
That's no btlejack issue, it is just your terminal (e.g. `bash`) telling you it cannot find a `btlejack` executable.
